[project]
name = "dataleak"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asgiref==3.11.1",
    "django==5.2.11",
    "python-dotenv==1.2.1",
    "sqlparse==0.5.5",
    "tzdata==2025.3",
    "uv==0.9.29",
]
